"""
Django settings for honglab project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1szk8qrut_ak!*z-p!p6)tm2#da0a=pv(snd(fjw(&4s0-m@ub'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'core',
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'honglab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'honglab.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Keycloak 설정
AUTHENTICATION_BACKENDS = (
    'social_core.backends.keycloak.KeycloakOAuth2',  # Keycloak 백엔드 추가
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_KEYCLOAK_KEY = '본인_키클락_클라이언트_이름'
SOCIAL_AUTH_KEYCLOAK_SECRET = '본인_키클락_클라이언트_시크릿'
SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY = '본인_키클락_퍼블릭_키'
SOCIAL_AUTH_KEYCLOAK_DOMAIN = '본인_키클락_도메인'
SOCIAL_AUTH_KEYCLOAK_REALM = '본인_키클락_REALM'
SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL = 'https://{domain}/realms/{realm}/protocol/openid-connect/auth'.format(domain=SOCIAL_AUTH_KEYCLOAK_DOMAIN, realm=SOCIAL_AUTH_KEYCLOAK_REALM)
SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL = 'https://{domain}/realms/{realm}/protocol/openid-connect/token'.format(domain=SOCIAL_AUTH_KEYCLOAK_DOMAIN, realm=SOCIAL_AUTH_KEYCLOAK_REALM)
SOCIAL_AUTH_KEYCLOAK_USERINFO_URL = 'https://{domain}/realms/{realm}/protocol/openid-connect/userinfo'.format(domain=SOCIAL_AUTH_KEYCLOAK_DOMAIN, realm=SOCIAL_AUTH_KEYCLOAK_REALM)
SOCIAL_AUTH_JWT_AUDIENCE = None

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'core.pipeline.save_keycloak_groups',
    'core.pipeline.rbac_for_admin',
)
